Audio File to Text

In [16]:
import librosa #manages audio files
import torch # importing pytorch
from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer

In [17]:
import IPython.display as display
file = display.Audio("file1.wav", autoplay=False)
file

In [18]:
# asudio files have to be 16kHz sampling rate
audio, rate = librosa.load('file1.wav', sr=16000)

In [19]:
audio #audio is float32


array([0.5583914 , 0.8553281 , 0.9956495 , ..., 0.10497018, 0.09035979,
       0.04638466], dtype=float32)

In [20]:
rate

16000

In [21]:
#import the pre-trained model

tokenizer = Wav2Vec2Tokenizer.from_pretrained('facebook/wav2vec2-base-960h')
model = Wav2Vec2ForCTC.from_pretrained('facebook/wav2vec2-base-960h')

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.
/home/ix502iv/miniconda3/envs/pytorch_env/lib/python3.10/site-packages/transformers/models/wav2vec2/tokenization_wav2vec2.py:746: FutureWarning: The class `Wav2Vec2Tokenizer` is deprecated and will be removed in version 5 of Transformers. Please use `Wav2Vec2Processor` or `Wav2Vec2CTCTokenizer` instead.
  warnings.warn(
Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [22]:
input_values = tokenizer(audio, return_tensors='pt').input_values
input_values

tensor([[ 1.3176,  2.0925,  2.4587,  ...,  0.1344,  0.0963, -0.0184]])

In [23]:
# get and store logits
logits = model(input_values).logits
logits

tensor([[[ 12.8000, -24.7575, -24.3624,  ...,  -5.9319,  -7.0408,  -5.8131],
         [ 12.8403, -24.7690, -24.3829,  ...,  -5.8503,  -6.9405,  -5.7722],
         [ 12.9161, -24.8252, -24.4360,  ...,  -5.8605,  -6.8903,  -5.7942],
         ...,
         [ 12.0048, -23.8485, -23.4921,  ...,  -5.6420,  -7.2383,  -5.0909],
         [ 12.1072, -23.8876, -23.5410,  ...,  -5.5500,  -7.0979,  -5.2135],
         [ 12.1760, -23.9628, -23.6034,  ...,  -5.6657,  -7.2424,  -5.3813]]],
       grad_fn=<ViewBackward0>)

In [24]:
# pass the logits to softmax to get the predicted values
prediction = torch.argmax(logits, dim=-1)

In [25]:
# convert the audio to text
transcription = tokenizer.batch_decode(prediction)[0]
transcription.capitalize()

'Identify wod in sixes i detifying wods in suxes identify wods in sixes'